server:
  port: 28082

spring:
  config:
    activate:
      on-profile: main
  application:
    name: task-core
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://172.20.0.6:5432/task-core}
    username: ${R2DBC_USERNAME:task_app}
    password: ${R2DBC_PASSWORD:Hjh761943!}
  jooq:
    sql-dialect: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

# SSE 설정 (운영용)
task:
  sse:
    heartbeat-seconds: 15

logging:
  level:
    root: info
    io.hcode: info
    org.jooq: info
    sql: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%15.15t]){faint} %clr([%8.8X{traceId:-}-%4.4X{spanId:-}]){cyan} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

management:
  otlp:
    tracing:
      endpoint: https://otel.hcode.ai.kr/v1/traces
      protocol: http/protobuf
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  tracing:
    sampling:
      probability: 1.0
